
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: brieflow_output/
preprocess:
  sbs_samples_fp: config/sbs_samples.tsv
  sbs_combo_fp: config/sbs_combo.tsv
  phenotype_samples_fp: config/phenotype_samples.tsv
  phenotype_combo_fp: config/phenotype_combo.tsv
  sbs_channel_order: null
  phenotype_channel_order: null
  phenotype_round_order:
  - 1
  - 2
  sbs_channel_order_flip: true
  phenotype_channel_order_flip: true
  sample_fraction: 0.5
sbs:
  alignment_method: null
  channel_names:
  - DAPI
  - Vimentin
  - G
  - T
  - A
  - C
  upsample_factor: 2
  skip_cycles_indices:
  - 0
  manual_background_cycle_index: 10
  extra_channel_indices:
  - 0
  - 1
  max_filter_width: 3
  spot_detection_method: standard
  dapi_cycle: 12
  cyto_cycle: 12
  cyto_cycle_index: 10
  dapi_index: 0
  cyto_index: 1
  segmentation_method: cellpose
  gpu: false
  reconcile: contained_in_cells
  segment_cells: true
  df_barcode_library_fp: config/barcode_library.tsv
  threshold_peaks: 200
  call_reads_method: median
  bases:
  - G
  - T
  - A
  - C
  q_min: 0
  barcode_col: sgRNA
  prefix_col: prefix
  error_correct: false
  sort_calls: count
  mode: null
  peak_width: 5
  nuclei_diameter: 9.304852983362556
  cell_diameter: 18.42058739751568
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 1
  cell_cellprob_threshold: 0
  cyto_model: cyto3
phenotype:
  foci_channel: 4
  channel_names:
  - DAPI
  - ACA
  - MITOTRACKER
  - VIMENTIN
  - CENPT
  - ITGB1
  - PHALLOIDIN
  - WGA
  align: true
  dapi_index: 0
  cyto_index: 3
  segmentation_method: cellpose
  reconcile: contained_in_cells
  gpu: false
  cp_method: cp_multichannel
  mode: null
  nuclei_diameter: 40.55891383898033
  cell_diameter: 66.87967195385028
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 1
  cell_cellprob_threshold: 0
  cyto_model: cyto3
  target: 0
  source: 5
  riders:
  - 6
  - 7
  - 8
  remove_channel: source
merge:
  merge_combo_fp: config/merge_combo.tsv
  sbs_metadata_cycle: 1
  sbs_metadata_channel: null
  ph_metadata_channel: null
  initial_sites:
  - - 5
    - 0
  - - 141
    - 32
  - - 370
    - 86
  - - 896
    - 212
  - - 1163
    - 270
  - - 1599
    - 376
  det_range:
  - 0.06
  - 0.065
  score: 0.1
  threshold: 2
aggregate:
  metadata_cols_fp: config/cell_data_metadata_cols.tsv
  collapse_cols:
  - sgRNA_0
  - gene_symbol_0
  classifier_path: config/binary_xgb_none_model.dill
  aggregate_combo_fp: config/aggregate_combo.tsv
  filter_queries:
  - mapped_single_gene == True
  perturbation_name_col: gene_symbol_0
  drop_cols_threshold: 0.1
  drop_rows_threshold: 0.01
  impute: true
  contamination: 0.01
  batch_cols:
  - plate
  - well
  control_key: nontargeting
  perturbation_id_col: sgRNA_0
  variance_or_ncomp: 0.99
  num_align_batches: 1
  agg_method: median
cluster:
  min_cell_cutoffs:
    Mitotic: 5
    Interphase: 5
    all: 5
  leiden_resolutions:
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  phate_distance_metric: cosine
  cluster_combo_fp: config/cluster_combo.tsv
  uniprot_data_fp: config/benchmark_clusters/uniprot_data.tsv
  string_pair_benchmark_fp: config/benchmark_clusters/string_pair_benchmark.tsv
  corum_group_benchmark_fp: config/benchmark_clusters/corum_group_benchmark.tsv
  kegg_group_benchmark_fp: config/benchmark_clusters/kegg_group_benchmark.tsv
